### ISSUE TITLE
Label 1337 is in the CSV but not in dataset folder

### ISSUE THREAD

**Issue by marcoleewow** [ml-hongkong/hongkong_flowers#7]
Label 1337 is in the CSV but not in dataset folder, which caused my dataloader to crash because my dataloader depends on .csv file. Right now I will remove this dependency and all should be good but this should be noted somewhere.

**Comment by indiejoseph** [comment]
Sorry, please rename 1327 to 1337, and remove "1327	Lantana camara	雪白馬纓丹" in csv
